# coding: utf-8

# flake8: noqa
"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.device_under_test import DeviceUnderTest
from openapi_client.models.func_string_task_boolean import FuncStringTaskBoolean
from openapi_client.models.product import Product
from openapi_client.models.project import Project
from openapi_client.models.release import Release
from openapi_client.models.result_type import ResultType
from openapi_client.models.script import Script
from openapi_client.models.script_repository import ScriptRepository
from openapi_client.models.test_build import TestBuild
from openapi_client.models.test_case import TestCase
from openapi_client.models.test_job import TestJob
from openapi_client.models.test_job_parameter import TestJobParameter
from openapi_client.models.test_job_report_template import TestJobReportTemplate
from openapi_client.models.test_machine import TestMachine
from openapi_client.models.test_plan import TestPlan
from openapi_client.models.test_plan_recipe import TestPlanRecipe
from openapi_client.models.test_report import TestReport
from openapi_client.models.test_result import TestResult
from openapi_client.models.test_suite import TestSuite
from openapi_client.models.user_credential import UserCredential
from openapi_client.models.test_environment import TestEnvironment
from openapi_client.models.test_parameter import TestParameter
from openapi_client.models.test_metadata import TestMetadata
