# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DeviceUnderTest(BaseModel):
    """
    DeviceUnderTest
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    machine_id: Optional[StrictInt] = Field(default=None, alias="machineId")
    product_id: Optional[StrictInt] = Field(default=None, alias="productId")
    product: Optional[Product] = Field(default=None, alias="Product")
    test_machine: Optional[TestMachine] = Field(default=None, alias="TestMachine")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "machineId", "productId", "Product", "TestMachine"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeviceUnderTest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of product
        if self.product:
            _dict['Product'] = self.product.to_dict()
        # override the default output from pydantic by calling `to_dict()` of test_machine
        if self.test_machine:
            _dict['TestMachine'] = self.test_machine.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeviceUnderTest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "machineId": obj.get("machineId"),
            "productId": obj.get("productId"),
            "Product": Product.from_dict(obj["Product"]) if obj.get("Product") is not None else None,
            "TestMachine": TestMachine.from_dict(obj["TestMachine"]) if obj.get("TestMachine") is not None else None
        })
        return _obj

from openapi_client.models.product import Product
from openapi_client.models.test_machine import TestMachine
# TODO: Rewrite to not use raise_errors
DeviceUnderTest.model_rebuild(raise_errors=False)

