# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Script(BaseModel):
    """
    Script
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    uri: Optional[StrictStr] = None
    script_repo_id: Optional[StrictInt] = Field(default=None, alias="scriptRepoId")
    command: Optional[StrictStr] = None
    script_repository: Optional[ScriptRepository] = Field(default=None, alias="ScriptRepository")
    test_cases: Optional[List[TestCase]] = Field(default=None, alias="TestCases")
    __properties: ClassVar[List[str]] = ["id", "name", "uri", "scriptRepoId", "command", "ScriptRepository", "TestCases"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Script from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of script_repository
        if self.script_repository:
            _dict['ScriptRepository'] = self.script_repository.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in test_cases (list)
        _items = []
        if self.test_cases:
            for _item_test_cases in self.test_cases:
                if _item_test_cases:
                    _items.append(_item_test_cases.to_dict())
            _dict['TestCases'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Script from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "uri": obj.get("uri"),
            "scriptRepoId": obj.get("scriptRepoId"),
            "command": obj.get("command"),
            "ScriptRepository": ScriptRepository.from_dict(obj["ScriptRepository"]) if obj.get("ScriptRepository") is not None else None,
            "TestCases": [TestCase.from_dict(_item) for _item in obj["TestCases"]] if obj.get("TestCases") is not None else None
        })
        return _obj

from openapi_client.models.script_repository import ScriptRepository
from openapi_client.models.test_case import TestCase
# TODO: Rewrite to not use raise_errors
Script.model_rebuild(raise_errors=False)

