# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestJob(BaseModel):
    """
    TestJob
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    credential_id: Optional[StrictInt] = Field(default=None, alias="credentialId")
    default_test_machine_id: Optional[StrictInt] = Field(default=None, alias="defaultTestMachineId")
    project_id: Optional[StrictInt] = Field(default=None, alias="projectId")
    project: Optional[Project] = Field(default=None, alias="Project")
    test_builds: Optional[List[TestBuild]] = Field(default=None, alias="TestBuilds")
    test_cases: Optional[List[TestCase]] = Field(default=None, alias="TestCases")
    user_credential: Optional[UserCredential] = Field(default=None, alias="UserCredential")
    test_job_parameters: Optional[List[TestJobParameter]] = Field(default=None, alias="TestJobParameters")
    test_job_report_templates: Optional[List[TestJobReportTemplate]] = Field(default=None, alias="TestJobReportTemplates")
    __properties: ClassVar[List[str]] = ["id", "name", "url", "credentialId", "defaultTestMachineId", "projectId", "Project", "TestBuilds", "TestCases", "UserCredential", "TestJobParameters", "TestJobReportTemplates"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of project
        if self.project:
            _dict['Project'] = self.project.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in test_builds (list)
        _items = []
        if self.test_builds:
            for _item_test_builds in self.test_builds:
                if _item_test_builds:
                    _items.append(_item_test_builds.to_dict())
            _dict['TestBuilds'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in test_cases (list)
        _items = []
        if self.test_cases:
            for _item_test_cases in self.test_cases:
                if _item_test_cases:
                    _items.append(_item_test_cases.to_dict())
            _dict['TestCases'] = _items
        # override the default output from pydantic by calling `to_dict()` of user_credential
        if self.user_credential:
            _dict['UserCredential'] = self.user_credential.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in test_job_parameters (list)
        _items = []
        if self.test_job_parameters:
            for _item_test_job_parameters in self.test_job_parameters:
                if _item_test_job_parameters:
                    _items.append(_item_test_job_parameters.to_dict())
            _dict['TestJobParameters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in test_job_report_templates (list)
        _items = []
        if self.test_job_report_templates:
            for _item_test_job_report_templates in self.test_job_report_templates:
                if _item_test_job_report_templates:
                    _items.append(_item_test_job_report_templates.to_dict())
            _dict['TestJobReportTemplates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "url": obj.get("url"),
            "credentialId": obj.get("credentialId"),
            "defaultTestMachineId": obj.get("defaultTestMachineId"),
            "projectId": obj.get("projectId"),
            "Project": Project.from_dict(obj["Project"]) if obj.get("Project") is not None else None,
            "TestBuilds": [TestBuild.from_dict(_item) for _item in obj["TestBuilds"]] if obj.get("TestBuilds") is not None else None,
            "TestCases": [TestCase.from_dict(_item) for _item in obj["TestCases"]] if obj.get("TestCases") is not None else None,
            "UserCredential": UserCredential.from_dict(obj["UserCredential"]) if obj.get("UserCredential") is not None else None,
            "TestJobParameters": [TestJobParameter.from_dict(_item) for _item in obj["TestJobParameters"]] if obj.get("TestJobParameters") is not None else None,
            "TestJobReportTemplates": [TestJobReportTemplate.from_dict(_item) for _item in obj["TestJobReportTemplates"]] if obj.get("TestJobReportTemplates") is not None else None
        })
        return _obj

from openapi_client.models.project import Project
from openapi_client.models.test_build import TestBuild
from openapi_client.models.test_case import TestCase
from openapi_client.models.test_job_parameter import TestJobParameter
from openapi_client.models.test_job_report_template import TestJobReportTemplate
from openapi_client.models.user_credential import UserCredential
# TODO: Rewrite to not use raise_errors
TestJob.model_rebuild(raise_errors=False)

