# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestBuild(BaseModel):
    """
    TestBuild
    """ # noqa: E501
    id: Optional[StrictInt] = None
    test_job_id: Optional[StrictInt] = Field(default=None, alias="testJobId")
    timestamp: Optional[datetime] = None
    build_result_id: Optional[StrictInt] = Field(default=None, alias="buildResultId")
    test_result_id: Optional[StrictInt] = Field(default=None, alias="testResultId")
    guid: Optional[UUID] = None
    start_time: Optional[datetime] = Field(default=None, alias="startTime")
    end_time: Optional[datetime] = Field(default=None, alias="endTime")
    timeout_hours: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="timeoutHours")
    result_type: Optional[ResultType] = Field(default=None, alias="ResultType")
    result_type1: Optional[ResultType] = Field(default=None, alias="ResultType1")
    test_job: Optional[TestJob] = Field(default=None, alias="TestJob")
    test_reports: Optional[List[TestReport]] = Field(default=None, alias="TestReports")
    test_results: Optional[List[TestResult]] = Field(default=None, alias="TestResults")
    __properties: ClassVar[List[str]] = ["id", "testJobId", "timestamp", "buildResultId", "testResultId", "guid", "startTime", "endTime", "timeoutHours", "ResultType", "ResultType1", "TestJob", "TestReports", "TestResults"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestBuild from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of result_type
        if self.result_type:
            _dict['ResultType'] = self.result_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of result_type1
        if self.result_type1:
            _dict['ResultType1'] = self.result_type1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of test_job
        if self.test_job:
            _dict['TestJob'] = self.test_job.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in test_reports (list)
        _items = []
        if self.test_reports:
            for _item_test_reports in self.test_reports:
                if _item_test_reports:
                    _items.append(_item_test_reports.to_dict())
            _dict['TestReports'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in test_results (list)
        _items = []
        if self.test_results:
            for _item_test_results in self.test_results:
                if _item_test_results:
                    _items.append(_item_test_results.to_dict())
            _dict['TestResults'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestBuild from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "testJobId": obj.get("testJobId"),
            "timestamp": obj.get("timestamp"),
            "buildResultId": obj.get("buildResultId"),
            "testResultId": obj.get("testResultId"),
            "guid": obj.get("guid"),
            "startTime": obj.get("startTime"),
            "endTime": obj.get("endTime"),
            "timeoutHours": obj.get("timeoutHours"),
            "ResultType": ResultType.from_dict(obj["ResultType"]) if obj.get("ResultType") is not None else None,
            "ResultType1": ResultType.from_dict(obj["ResultType1"]) if obj.get("ResultType1") is not None else None,
            "TestJob": TestJob.from_dict(obj["TestJob"]) if obj.get("TestJob") is not None else None,
            "TestReports": [TestReport.from_dict(_item) for _item in obj["TestReports"]] if obj.get("TestReports") is not None else None,
            "TestResults": [TestResult.from_dict(_item) for _item in obj["TestResults"]] if obj.get("TestResults") is not None else None
        })
        return _obj

from openapi_client.models.result_type import ResultType
from openapi_client.models.test_job import TestJob
from openapi_client.models.test_report import TestReport
from openapi_client.models.test_result import TestResult
# TODO: Rewrite to not use raise_errors
TestBuild.model_rebuild(raise_errors=False)

