# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestJobParameter(BaseModel):
    """
    TestJobParameter
    """ # noqa: E501
    id: Optional[StrictInt] = None
    test_job_id: Optional[StrictInt] = Field(default=None, alias="testJobId")
    name: Optional[StrictStr] = None
    value: Optional[StrictStr] = None
    default_value: Optional[StrictStr] = Field(default=None, alias="defaultValue")
    test_job: Optional[TestJob] = Field(default=None, alias="TestJob")
    __properties: ClassVar[List[str]] = ["id", "testJobId", "name", "value", "defaultValue", "TestJob"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestJobParameter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of test_job
        if self.test_job:
            _dict['TestJob'] = self.test_job.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestJobParameter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "testJobId": obj.get("testJobId"),
            "name": obj.get("name"),
            "value": obj.get("value"),
            "defaultValue": obj.get("defaultValue"),
            "TestJob": TestJob.from_dict(obj["TestJob"]) if obj.get("TestJob") is not None else None
        })
        return _obj

from openapi_client.models.test_job import TestJob
# TODO: Rewrite to not use raise_errors
TestJobParameter.model_rebuild(raise_errors=False)

