# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.func_string_task_boolean import FuncStringTaskBoolean

class TestFuncStringTaskBoolean(unittest.TestCase):
    """FuncStringTaskBoolean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FuncStringTaskBoolean:
        """Test FuncStringTaskBoolean
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FuncStringTaskBoolean`
        """
        model = FuncStringTaskBoolean()
        if include_optional:
            return FuncStringTaskBoolean(
                method = None,
                target = None
            )
        else:
            return FuncStringTaskBoolean(
        )
        """

    def testFuncStringTaskBoolean(self):
        """Test FuncStringTaskBoolean"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
