# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dashboard_api import DashboardApi


class TestDashboardApi(unittest.TestCase):
    """DashboardApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DashboardApi()

    def tearDown(self) -> None:
        pass

    def test_dashboard_delete(self) -> None:
        """Test case for dashboard_delete

        """
        pass

    def test_dashboard_get(self) -> None:
        """Test case for dashboard_get

        """
        pass

    def test_dashboard_get_0(self) -> None:
        """Test case for dashboard_get_0

        """
        pass

    def test_dashboard_post(self) -> None:
        """Test case for dashboard_post

        """
        pass

    def test_dashboard_put(self) -> None:
        """Test case for dashboard_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
