# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.project_api import ProjectApi


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectApi()

    def tearDown(self) -> None:
        pass

    def test_project_delete(self) -> None:
        """Test case for project_delete

        """
        pass

    def test_project_get(self) -> None:
        """Test case for project_get

        """
        pass

    def test_project_get_0(self) -> None:
        """Test case for project_get_0

        """
        pass

    def test_project_id(self) -> None:
        """Test case for project_id

        """
        pass

    def test_project_post(self) -> None:
        """Test case for project_post

        """
        pass

    def test_project_put(self) -> None:
        """Test case for project_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
