# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.test_build_api import TestBuildApi


class TestTestBuildApi(unittest.TestCase):
    """TestBuildApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestBuildApi()

    def tearDown(self) -> None:
        pass

    def test_test_build_build_list(self) -> None:
        """Test case for test_build_build_list

        """
        pass

    def test_test_build_delete(self) -> None:
        """Test case for test_build_delete

        """
        pass

    def test_test_build_get(self) -> None:
        """Test case for test_build_get

        """
        pass

    def test_test_build_get_0(self) -> None:
        """Test case for test_build_get_0

        """
        pass

    def test_test_build_guid(self) -> None:
        """Test case for test_build_guid

        """
        pass

    def test_test_build_id(self) -> None:
        """Test case for test_build_id

        """
        pass

    def test_test_build_last(self) -> None:
        """Test case for test_build_last

        """
        pass

    def test_test_build_last_success(self) -> None:
        """Test case for test_build_last_success

        """
        pass

    def test_test_build_post(self) -> None:
        """Test case for test_build_post

        """
        pass

    def test_test_build_put(self) -> None:
        """Test case for test_build_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
