# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.test_machine import TestMachine

class TestTestMachine(unittest.TestCase):
    """TestMachine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestMachine:
        """Test TestMachine
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestMachine`
        """
        model = TestMachine()
        if include_optional:
            return TestMachine(
                id = 56,
                name = '',
                address = '',
                credential_id = 56,
                device_under_tests = [
                    openapi_client.models.device_under_test.DeviceUnderTest(
                        id = 56, 
                        name = '', 
                        description = '', 
                        machine_id = 56, 
                        product_id = 56, 
                        product = openapi_client.models.product.Product(
                            id = 56, 
                            name = '', 
                            description = '', 
                            projects = [
                                openapi_client.models.project.Project(
                                    id = 56, 
                                    name = '', 
                                    description = '', 
                                    product_id = 56, 
                                    test_jobs = [
                                        openapi_client.models.test_job.TestJob(
                                            id = 56, 
                                            name = '', 
                                            url = '', 
                                            credential_id = 56, 
                                            default_test_machine_id = 56, 
                                            project_id = 56, 
                                            test_builds = [
                                                openapi_client.models.test_build.TestBuild(
                                                    id = 56, 
                                                    test_job_id = 56, 
                                                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                    build_result_id = 56, 
                                                    test_result_id = 56, 
                                                    guid = '00000000-0000-0000-0000-000000000000', 
                                                    start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                    end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                    timeout_hours = 1.337, 
                                                    result_type = openapi_client.models.result_type.ResultType(
                                                        id = 56, 
                                                        name = '', 
                                                        test_builds1 = [
                                                            openapi_client.models.test_build.TestBuild(
                                                                id = 56, 
                                                                test_job_id = 56, 
                                                                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                                build_result_id = 56, 
                                                                test_result_id = 56, 
                                                                guid = '00000000-0000-0000-0000-000000000000', 
                                                                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                                timeout_hours = 1.337, 
                                                                result_type1 = openapi_client.models.result_type.ResultType(
                                                                    id = 56, 
                                                                    name = '', 
                                                                    test_results = [
                                                                        openapi_client.models.test_result.TestResult(
                                                                            id = 56, 
                                                                            test_build_id = 56, 
                                                                            test_result_id = 56, )
                                                                        ], ), 
                                                                test_reports = [
                                                                    openapi_client.models.test_report.TestReport(
                                                                        id = 56, 
                                                                        name = '', 
                                                                        report = '', 
                                                                        build_id = 56, 
                                                                        test_report_template_id = 56, 
                                                                        test_job_report_template = openapi_client.models.test_job_report_template.TestJobReportTemplate(
                                                                            id = 56, 
                                                                            name = '', 
                                                                            template = '', 
                                                                            test_job_id = 56, 
                                                                            email_to = '', 
                                                                            email_cc = '', 
                                                                            email_bcc = '', ), )
                                                                    ], 
                                                                test_results = [
                                                                    openapi_client.models.test_result.TestResult(
                                                                        id = 56, 
                                                                        test_build_id = 56, 
                                                                        test_result_id = 56, )
                                                                    ], )
                                                            ], 
                                                        test_results = , ), 
                                                    result_type1 = , 
                                                    test_reports = [
                                                        openapi_client.models.test_report.TestReport(
                                                            id = 56, 
                                                            name = '', 
                                                            report = '', 
                                                            build_id = 56, 
                                                            test_report_template_id = 56, )
                                                        ], 
                                                    test_results = , )
                                                ], 
                                            test_cases = [
                                                openapi_client.models.test_case.TestCase(
                                                    id = 56, 
                                                    job_id = 56, 
                                                    script_id = 56, 
                                                    script = openapi_client.models.script.Script(
                                                        id = 56, 
                                                        name = '', 
                                                        uri = '', 
                                                        script_repo_id = 56, 
                                                        command = '', 
                                                        script_repository = openapi_client.models.script_repository.ScriptRepository(
                                                            id = 56, 
                                                            name = '', 
                                                            url = '', 
                                                            scripts = [
                                                                openapi_client.models.script.Script(
                                                                    id = 56, 
                                                                    name = '', 
                                                                    uri = '', 
                                                                    script_repo_id = 56, 
                                                                    command = '', )
                                                                ], ), ), 
                                                    test_plan_recipes = [
                                                        openapi_client.models.test_plan_recipe.TestPlanRecipe(
                                                            id = 56, 
                                                            test_plan_id = 56, 
                                                            test_suit_id = 56, 
                                                            test_case_id = 56, 
                                                            schedual = '', 
                                                            test_plan = openapi_client.models.test_plan.TestPlan(
                                                                id = 56, 
                                                                name = '', 
                                                                description = '', 
                                                                product_id = 56, ), 
                                                            test_suite = openapi_client.models.test_suite.TestSuite(
                                                                id = 56, 
                                                                name = '', ), )
                                                        ], )
                                                ], 
                                            user_credential = openapi_client.models.user_credential.UserCredential(
                                                id = 56, 
                                                user_name = '', 
                                                password = '', 
                                                token = '', 
                                                description = '', 
                                                createdby = '', 
                                                scope = '', 
                                                test_machines = [
                                                    openapi_client.models.test_machine.TestMachine(
                                                        id = 56, 
                                                        name = '', 
                                                        address = '', 
                                                        credential_id = 56, )
                                                    ], ), 
                                            test_job_parameters = [
                                                openapi_client.models.test_job_parameter.TestJobParameter(
                                                    id = 56, 
                                                    test_job_id = 56, 
                                                    name = '', 
                                                    value = '', 
                                                    default_value = '', )
                                                ], 
                                            test_job_report_templates = [
                                                openapi_client.models.test_job_report_template.TestJobReportTemplate(
                                                    id = 56, 
                                                    name = '', 
                                                    template = '', 
                                                    test_job_id = 56, 
                                                    email_to = '', 
                                                    email_cc = '', 
                                                    email_bcc = '', )
                                                ], )
                                        ], )
                                ], 
                            release = openapi_client.models.release.Release(
                                id = 56, 
                                version = '', 
                                product_id = 56, ), 
                            test_plans = [
                                openapi_client.models.test_plan.TestPlan(
                                    id = 56, 
                                    name = '', 
                                    description = '', 
                                    product_id = 56, )
                                ], ), 
                        test_machine = openapi_client.models.test_machine.TestMachine(
                            id = 56, 
                            name = '', 
                            address = '', 
                            credential_id = 56, ), )
                    ],
                user_credential = openapi_client.models.user_credential.UserCredential(
                    id = 56, 
                    user_name = '', 
                    password = '', 
                    token = '', 
                    description = '', 
                    createdby = '', 
                    scope = '', 
                    test_jobs = [
                        openapi_client.models.test_job.TestJob(
                            id = 56, 
                            name = '', 
                            url = '', 
                            credential_id = 56, 
                            default_test_machine_id = 56, 
                            project_id = 56, 
                            project = openapi_client.models.project.Project(
                                id = 56, 
                                name = '', 
                                description = '', 
                                product_id = 56, 
                                product = openapi_client.models.product.Product(
                                    id = 56, 
                                    name = '', 
                                    description = '', 
                                    device_under_tests = [
                                        openapi_client.models.device_under_test.DeviceUnderTest(
                                            id = 56, 
                                            name = '', 
                                            description = '', 
                                            machine_id = 56, 
                                            product_id = 56, 
                                            test_machine = openapi_client.models.test_machine.TestMachine(
                                                id = 56, 
                                                name = '', 
                                                address = '', 
                                                credential_id = 56, ), )
                                        ], 
                                    projects = [
                                        openapi_client.models.project.Project(
                                            id = 56, 
                                            name = '', 
                                            description = '', 
                                            product_id = 56, )
                                        ], 
                                    release = openapi_client.models.release.Release(
                                        id = 56, 
                                        version = '', 
                                        product_id = 56, ), 
                                    test_plans = [
                                        openapi_client.models.test_plan.TestPlan(
                                            id = 56, 
                                            name = '', 
                                            description = '', 
                                            product_id = 56, 
                                            test_plan_recipes = [
                                                openapi_client.models.test_plan_recipe.TestPlanRecipe(
                                                    id = 56, 
                                                    test_plan_id = 56, 
                                                    test_suit_id = 56, 
                                                    test_case_id = 56, 
                                                    schedual = '', 
                                                    test_case = openapi_client.models.test_case.TestCase(
                                                        id = 56, 
                                                        job_id = 56, 
                                                        script_id = 56, 
                                                        script = openapi_client.models.script.Script(
                                                            id = 56, 
                                                            name = '', 
                                                            uri = '', 
                                                            script_repo_id = 56, 
                                                            command = '', 
                                                            script_repository = openapi_client.models.script_repository.ScriptRepository(
                                                                id = 56, 
                                                                name = '', 
                                                                url = '', 
                                                                scripts = [
                                                                    openapi_client.models.script.Script(
                                                                        id = 56, 
                                                                        name = '', 
                                                                        uri = '', 
                                                                        script_repo_id = 56, 
                                                                        command = '', 
                                                                        test_cases = [
                                                                            openapi_client.models.test_case.TestCase(
                                                                                id = 56, 
                                                                                job_id = 56, 
                                                                                script_id = 56, )
                                                                            ], )
                                                                    ], ), 
                                                            test_cases = [
                                                                
                                                                ], ), ), 
                                                    test_suite = openapi_client.models.test_suite.TestSuite(
                                                        id = 56, 
                                                        name = '', ), )
                                                ], )
                                        ], ), ), 
                            test_builds = [
                                openapi_client.models.test_build.TestBuild(
                                    id = 56, 
                                    test_job_id = 56, 
                                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    build_result_id = 56, 
                                    test_result_id = 56, 
                                    guid = '00000000-0000-0000-0000-000000000000', 
                                    start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    timeout_hours = 1.337, 
                                    result_type = openapi_client.models.result_type.ResultType(
                                        id = 56, 
                                        name = '', 
                                        test_builds1 = [
                                            openapi_client.models.test_build.TestBuild(
                                                id = 56, 
                                                test_job_id = 56, 
                                                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                build_result_id = 56, 
                                                test_result_id = 56, 
                                                guid = '00000000-0000-0000-0000-000000000000', 
                                                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                timeout_hours = 1.337, 
                                                result_type1 = openapi_client.models.result_type.ResultType(
                                                    id = 56, 
                                                    name = '', 
                                                    test_results = [
                                                        openapi_client.models.test_result.TestResult(
                                                            id = 56, 
                                                            test_build_id = 56, 
                                                            test_result_id = 56, )
                                                        ], ), 
                                                test_reports = [
                                                    openapi_client.models.test_report.TestReport(
                                                        id = 56, 
                                                        name = '', 
                                                        report = '', 
                                                        build_id = 56, 
                                                        test_report_template_id = 56, 
                                                        test_job_report_template = openapi_client.models.test_job_report_template.TestJobReportTemplate(
                                                            id = 56, 
                                                            name = '', 
                                                            template = '', 
                                                            test_job_id = 56, 
                                                            email_to = '', 
                                                            email_cc = '', 
                                                            email_bcc = '', ), )
                                                    ], 
                                                test_results = [
                                                    openapi_client.models.test_result.TestResult(
                                                        id = 56, 
                                                        test_build_id = 56, 
                                                        test_result_id = 56, )
                                                    ], )
                                            ], 
                                        test_results = , ), 
                                    result_type1 = , 
                                    test_reports = [
                                        openapi_client.models.test_report.TestReport(
                                            id = 56, 
                                            name = '', 
                                            report = '', 
                                            build_id = 56, 
                                            test_report_template_id = 56, )
                                        ], 
                                    test_results = , )
                                ], 
                            test_cases = , 
                            test_job_parameters = [
                                openapi_client.models.test_job_parameter.TestJobParameter(
                                    id = 56, 
                                    test_job_id = 56, 
                                    name = '', 
                                    value = '', 
                                    default_value = '', )
                                ], 
                            test_job_report_templates = [
                                openapi_client.models.test_job_report_template.TestJobReportTemplate(
                                    id = 56, 
                                    name = '', 
                                    template = '', 
                                    test_job_id = 56, 
                                    email_to = '', 
                                    email_cc = '', 
                                    email_bcc = '', )
                                ], )
                        ], 
                    test_machines = [
                        openapi_client.models.test_machine.TestMachine(
                            id = 56, 
                            name = '', 
                            address = '', 
                            credential_id = 56, )
                        ], )
            )
        else:
            return TestMachine(
        )
        """

    def testTestMachine(self):
        """Test TestMachine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
