# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.test_job_api import TestJobApi


class TestTestJobApi(unittest.TestCase):
    """TestJobApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestJobApi()

    def tearDown(self) -> None:
        pass

    def test_test_job_delete(self) -> None:
        """Test case for test_job_delete

        """
        pass

    def test_test_job_get(self) -> None:
        """Test case for test_job_get

        """
        pass

    def test_test_job_get_0(self) -> None:
        """Test case for test_job_get_0

        """
        pass

    def test_test_job_id(self) -> None:
        """Test case for test_job_id

        """
        pass

    def test_test_job_post(self) -> None:
        """Test case for test_job_post

        """
        pass

    def test_test_job_put(self) -> None:
        """Test case for test_job_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
