# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Product(BaseModel):
    """
    Product
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    device_under_tests: Optional[List[DeviceUnderTest]] = Field(default=None, alias="DeviceUnderTests")
    projects: Optional[List[Project]] = Field(default=None, alias="Projects")
    release: Optional[Release] = Field(default=None, alias="Release")
    test_plans: Optional[List[TestPlan]] = Field(default=None, alias="TestPlans")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "DeviceUnderTests", "Projects", "Release", "TestPlans"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Product from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in device_under_tests (list)
        _items = []
        if self.device_under_tests:
            for _item_device_under_tests in self.device_under_tests:
                if _item_device_under_tests:
                    _items.append(_item_device_under_tests.to_dict())
            _dict['DeviceUnderTests'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in projects (list)
        _items = []
        if self.projects:
            for _item_projects in self.projects:
                if _item_projects:
                    _items.append(_item_projects.to_dict())
            _dict['Projects'] = _items
        # override the default output from pydantic by calling `to_dict()` of release
        if self.release:
            _dict['Release'] = self.release.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in test_plans (list)
        _items = []
        if self.test_plans:
            for _item_test_plans in self.test_plans:
                if _item_test_plans:
                    _items.append(_item_test_plans.to_dict())
            _dict['TestPlans'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Product from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "DeviceUnderTests": [DeviceUnderTest.from_dict(_item) for _item in obj["DeviceUnderTests"]] if obj.get("DeviceUnderTests") is not None else None,
            "Projects": [Project.from_dict(_item) for _item in obj["Projects"]] if obj.get("Projects") is not None else None,
            "Release": Release.from_dict(obj["Release"]) if obj.get("Release") is not None else None,
            "TestPlans": [TestPlan.from_dict(_item) for _item in obj["TestPlans"]] if obj.get("TestPlans") is not None else None
        })
        return _obj

from openapi_client.models.device_under_test import DeviceUnderTest
from openapi_client.models.project import Project
from openapi_client.models.release import Release
from openapi_client.models.test_plan import TestPlan
# TODO: Rewrite to not use raise_errors
Product.model_rebuild(raise_errors=False)

