# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestPlanRecipe(BaseModel):
    """
    TestPlanRecipe
    """ # noqa: E501
    id: Optional[StrictInt] = None
    test_plan_id: Optional[StrictInt] = Field(default=None, alias="testPlanId")
    test_suit_id: Optional[StrictInt] = Field(default=None, alias="testSuitId")
    test_case_id: Optional[StrictInt] = Field(default=None, alias="testCaseId")
    schedual: Optional[StrictStr] = None
    test_case: Optional[TestCase] = Field(default=None, alias="TestCase")
    test_plan: Optional[TestPlan] = Field(default=None, alias="TestPlan")
    test_suite: Optional[TestSuite] = Field(default=None, alias="TestSuite")
    __properties: ClassVar[List[str]] = ["id", "testPlanId", "testSuitId", "testCaseId", "schedual", "TestCase", "TestPlan", "TestSuite"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestPlanRecipe from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of test_case
        if self.test_case:
            _dict['TestCase'] = self.test_case.to_dict()
        # override the default output from pydantic by calling `to_dict()` of test_plan
        if self.test_plan:
            _dict['TestPlan'] = self.test_plan.to_dict()
        # override the default output from pydantic by calling `to_dict()` of test_suite
        if self.test_suite:
            _dict['TestSuite'] = self.test_suite.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestPlanRecipe from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "testPlanId": obj.get("testPlanId"),
            "testSuitId": obj.get("testSuitId"),
            "testCaseId": obj.get("testCaseId"),
            "schedual": obj.get("schedual"),
            "TestCase": TestCase.from_dict(obj["TestCase"]) if obj.get("TestCase") is not None else None,
            "TestPlan": TestPlan.from_dict(obj["TestPlan"]) if obj.get("TestPlan") is not None else None,
            "TestSuite": TestSuite.from_dict(obj["TestSuite"]) if obj.get("TestSuite") is not None else None
        })
        return _obj

from openapi_client.models.test_case import TestCase
from openapi_client.models.test_plan import TestPlan
from openapi_client.models.test_suite import TestSuite
# TODO: Rewrite to not use raise_errors
TestPlanRecipe.model_rebuild(raise_errors=False)

