# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestJobReportTemplate(BaseModel):
    """
    TestJobReportTemplate
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    template: Optional[StrictStr] = None
    test_job_id: Optional[StrictInt] = Field(default=None, alias="testJobId")
    email_to: Optional[StrictStr] = Field(default=None, alias="emailTo")
    email_cc: Optional[StrictStr] = Field(default=None, alias="emailCc")
    email_bcc: Optional[StrictStr] = Field(default=None, alias="emailBcc")
    test_job: Optional[TestJob] = Field(default=None, alias="TestJob")
    test_reports: Optional[List[TestReport]] = Field(default=None, alias="TestReports")
    __properties: ClassVar[List[str]] = ["id", "name", "template", "testJobId", "emailTo", "emailCc", "emailBcc", "TestJob", "TestReports"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestJobReportTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of test_job
        if self.test_job:
            _dict['TestJob'] = self.test_job.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in test_reports (list)
        _items = []
        if self.test_reports:
            for _item_test_reports in self.test_reports:
                if _item_test_reports:
                    _items.append(_item_test_reports.to_dict())
            _dict['TestReports'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestJobReportTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "template": obj.get("template"),
            "testJobId": obj.get("testJobId"),
            "emailTo": obj.get("emailTo"),
            "emailCc": obj.get("emailCc"),
            "emailBcc": obj.get("emailBcc"),
            "TestJob": TestJob.from_dict(obj["TestJob"]) if obj.get("TestJob") is not None else None,
            "TestReports": [TestReport.from_dict(_item) for _item in obj["TestReports"]] if obj.get("TestReports") is not None else None
        })
        return _obj

from openapi_client.models.test_job import TestJob
from openapi_client.models.test_report import TestReport
# TODO: Rewrite to not use raise_errors
TestJobReportTemplate.model_rebuild(raise_errors=False)

