# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestCase(BaseModel):
    """
    TestCase
    """ # noqa: E501
    id: Optional[StrictInt] = None
    job_id: Optional[StrictInt] = Field(default=None, alias="jobId")
    script_id: Optional[StrictInt] = Field(default=None, alias="scriptId")
    script: Optional[Script] = Field(default=None, alias="Script")
    test_job: Optional[TestJob] = Field(default=None, alias="TestJob")
    test_plan_recipes: Optional[List[TestPlanRecipe]] = Field(default=None, alias="TestPlanRecipes")
    __properties: ClassVar[List[str]] = ["id", "jobId", "scriptId", "Script", "TestJob", "TestPlanRecipes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestCase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of script
        if self.script:
            _dict['Script'] = self.script.to_dict()
        # override the default output from pydantic by calling `to_dict()` of test_job
        if self.test_job:
            _dict['TestJob'] = self.test_job.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in test_plan_recipes (list)
        _items = []
        if self.test_plan_recipes:
            for _item_test_plan_recipes in self.test_plan_recipes:
                if _item_test_plan_recipes:
                    _items.append(_item_test_plan_recipes.to_dict())
            _dict['TestPlanRecipes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestCase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "jobId": obj.get("jobId"),
            "scriptId": obj.get("scriptId"),
            "Script": Script.from_dict(obj["Script"]) if obj.get("Script") is not None else None,
            "TestJob": TestJob.from_dict(obj["TestJob"]) if obj.get("TestJob") is not None else None,
            "TestPlanRecipes": [TestPlanRecipe.from_dict(_item) for _item in obj["TestPlanRecipes"]] if obj.get("TestPlanRecipes") is not None else None
        })
        return _obj

from openapi_client.models.script import Script
from openapi_client.models.test_job import TestJob
from openapi_client.models.test_plan_recipe import TestPlanRecipe
# TODO: Rewrite to not use raise_errors
TestCase.model_rebuild(raise_errors=False)

