# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TestReport(BaseModel):
    """
    TestReport
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    report: Optional[StrictStr] = None
    build_id: Optional[StrictInt] = Field(default=None, alias="buildId")
    test_report_template_id: Optional[StrictInt] = Field(default=None, alias="testReportTemplateId")
    test_build: Optional[TestBuild] = Field(default=None, alias="TestBuild")
    test_job_report_template: Optional[TestJobReportTemplate] = Field(default=None, alias="TestJobReportTemplate")
    __properties: ClassVar[List[str]] = ["id", "name", "report", "buildId", "testReportTemplateId", "TestBuild", "TestJobReportTemplate"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestReport from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of test_build
        if self.test_build:
            _dict['TestBuild'] = self.test_build.to_dict()
        # override the default output from pydantic by calling `to_dict()` of test_job_report_template
        if self.test_job_report_template:
            _dict['TestJobReportTemplate'] = self.test_job_report_template.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestReport from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "report": obj.get("report"),
            "buildId": obj.get("buildId"),
            "testReportTemplateId": obj.get("testReportTemplateId"),
            "TestBuild": TestBuild.from_dict(obj["TestBuild"]) if obj.get("TestBuild") is not None else None,
            "TestJobReportTemplate": TestJobReportTemplate.from_dict(obj["TestJobReportTemplate"]) if obj.get("TestJobReportTemplate") is not None else None
        })
        return _obj

from openapi_client.models.test_build import TestBuild
from openapi_client.models.test_job_report_template import TestJobReportTemplate
# TODO: Rewrite to not use raise_errors
TestReport.model_rebuild(raise_errors=False)

