# coding: utf-8

"""
    prism.web.service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserCredential(BaseModel):
    """
    UserCredential
    """ # noqa: E501
    id: Optional[StrictInt] = None
    user_name: Optional[StrictStr] = Field(default=None, alias="userName")
    password: Optional[StrictStr] = None
    token: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    createdby: Optional[StrictStr] = None
    scope: Optional[StrictStr] = None
    test_jobs: Optional[List[TestJob]] = Field(default=None, alias="TestJobs")
    test_machines: Optional[List[TestMachine]] = Field(default=None, alias="TestMachines")
    __properties: ClassVar[List[str]] = ["id", "userName", "password", "token", "description", "createdby", "scope", "TestJobs", "TestMachines"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserCredential from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in test_jobs (list)
        _items = []
        if self.test_jobs:
            for _item_test_jobs in self.test_jobs:
                if _item_test_jobs:
                    _items.append(_item_test_jobs.to_dict())
            _dict['TestJobs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in test_machines (list)
        _items = []
        if self.test_machines:
            for _item_test_machines in self.test_machines:
                if _item_test_machines:
                    _items.append(_item_test_machines.to_dict())
            _dict['TestMachines'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserCredential from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "userName": obj.get("userName"),
            "password": obj.get("password"),
            "token": obj.get("token"),
            "description": obj.get("description"),
            "createdby": obj.get("createdby"),
            "scope": obj.get("scope"),
            "TestJobs": [TestJob.from_dict(_item) for _item in obj["TestJobs"]] if obj.get("TestJobs") is not None else None,
            "TestMachines": [TestMachine.from_dict(_item) for _item in obj["TestMachines"]] if obj.get("TestMachines") is not None else None
        })
        return _obj

from openapi_client.models.test_job import TestJob
from openapi_client.models.test_machine import TestMachine
# TODO: Rewrite to not use raise_errors
UserCredential.model_rebuild(raise_errors=False)

